exclude = [
    ".git",
    ".git-rewrite",
    ".ipynb_checkpoints",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    ".vscode",
    "__pypackages__",
    "dist",
    "venv",
    "ruff.toml",
]
line-length = 99
target-version = "py312"

[lint]
select = ["ALL"]
ignore = [
    "D104", # Missing docstring in public package
    "D103", # Missing docstring in public function
    "D100", # Missing docstring in public module
    "COM812", # Missing trailing comma
    "T201", # Prints
    "NPY002", # random.Generator instead of legacy random.choice
]
fixable = ["ALL"]
unfixable = []

[format]
quote-style = "double"
docstring-code-format = true
skip-magic-trailing-comma = true

[lint.pydocstyle]
convention = "google"

[lint.isort]
split-on-trailing-comma = false